services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic.ru-central1.internal:9200
    ports:
      - "5601:5601"
